# Generated by Django 5.2.15 on 2026-06-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_usersecurityquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Database', 'Database'), ('Web Development', 'Web Development'), ('AI/ML', 'AI/ML'), ('Cybersecurity', 'Cybersecurity'), ('Cloud', 'Cloud'), ('Tools', 'Tools'), ('Soft Skill', 'Soft Skill')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.skill')),
            ],
            options={
                'unique_together': {('job_role', 'skill')},
            },
        ),
    ]
