# Generated by Django 5.2.15 on 2026-06-19 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0003_jobrole_skill_jobroleskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobroleskill',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CareerMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
                ('matched_skills', models.ManyToManyField(blank=True, related_name='matched_skills', to='career_app.skill')),
                ('missing_skills', models.ManyToManyField(blank=True, related_name='missing_skills', to='career_app.skill')),
                ('selected_skills', models.ManyToManyField(related_name='selected_skills', to='career_app.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
