# Generated by Django 5.2.15 on 2026-06-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0004_alter_jobroleskill_unique_together_careermatchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('Course', 'Course'), ('Video', 'Video'), ('Documentation', 'Documentation'), ('Book', 'Book'), ('Article', 'Article')], max_length=50)),
                ('url', models.URLField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.skill')),
            ],
        ),
    ]
