# Generated by Django 5.2.15 on 2026-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extracted_skills',
            field=models.ManyToManyField(blank=True, to='career_app.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_resume_valid',
            field=models.BooleanField(default=False),
        ),
    ]
