# Generated by Django 5.2.15 on 2026-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0008_readinessassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual_skills',
            field=models.ManyToManyField(blank=True, related_name='manual_user_profiles', to='career_app.skill'),
        ),
    ]
