# Generated by Django 5.2.15 on 2026-06-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0009_userprofile_manual_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Development Tool', 'Development Tool'), ('Data Tool', 'Data Tool'), ('Cloud Tool', 'Cloud Tool'), ('AI/ML Tool', 'AI/ML Tool'), ('Testing Tool', 'Testing Tool'), ('DevOps Tool', 'DevOps Tool')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.industrytool')),
            ],
            options={
                'unique_together': {('job_role', 'tool')},
            },
        ),
    ]
