# Generated by Django 5.2.15 on 2026-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0010_industrytool_jobroletool'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manual_tools',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='career_app.industrytool'),
        ),
    ]
