# Generated by Django 5.2.15 on 2026-06-24 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0011_userprofile_manual_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployabilityBottleneck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_bottleneck', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
                ('readiness_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.readinessassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
