# Generated by Django 5.2.15 on 2026-06-24 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0013_userproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTransitionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_match_score', models.FloatField(default=0)),
                ('tool_match_score', models.FloatField(default=0)),
                ('feasibility_score', models.FloatField(default=0)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('missing_skills', models.TextField(blank=True, null=True)),
                ('missing_tools', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_transition_roles', to='career_app.jobrole')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transition_roles', to='career_app.jobrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
