# Generated by Django 5.2.15 on 2026-06-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0014_careertransitionanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('rule', models.CharField(choices=[('ALL_REQUIRED', 'All Required'), ('ANY_ONE', 'Any One')], default='ANY_ONE', max_length=20)),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
                ('skills', models.ManyToManyField(to='career_app.skill')),
            ],
            options={
                'unique_together': {('job_role', 'group_name')},
            },
        ),
    ]
