# Generated by Django 5.2.15 on 2026-06-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0015_skillrequirementgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('rule', models.CharField(choices=[('ANY_ONE', 'Any One'), ('ALL_REQUIRED', 'All Required')], default='ANY_ONE', max_length=20)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobrole')),
            ],
            options={
                'unique_together': {('job_role', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='career_app.competencygroup')),
                ('job_role_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobroleskill')),
            ],
            options={
                'unique_together': {('group', 'job_role_skill')},
            },
        ),
        migrations.DeleteModel(
            name='SkillRequirementGroup',
        ),
    ]
