# Generated by Django 5.2.15 on 2026-06-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0016_competencygroup_competencygroupmember_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobroleskill',
            unique_together={('job_role', 'skill')},
        ),
    ]
