# Generated by Django 5.2.15 on 2026-07-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0018_interviewquestion_interviewanswer_interviewsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='competency_group',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='expected_skill',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='expected_tool',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='bottleneck',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='project',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='readiness_assessment',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterviewAnswer',
        ),
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
    ]
