# Generated by Django 5.2.15 on 2026-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0020_interviewquestion_interviewanswer_interviewsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
