# Generated by Django 5.2.15 on 2026-07-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0021_interviewanswer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanswer',
            name='score',
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='communication_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='improved_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='technical_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
