# Generated by Django 5.2.15 on 2026-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0023_interviewsession_evaluation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='project_type',
            field=models.CharField(choices=[('WEB_APP', 'Web Application'), ('MOBILE_APP', 'Mobile Application'), ('DESKTOP_APP', 'Desktop Application'), ('BACKEND_API', 'Backend / REST API'), ('AI_ML', 'AI / Machine Learning Project'), ('DATA', 'Data / Analytics Project'), ('CLOUD_DEVOPS', 'Cloud / DevOps Project'), ('GAME', 'Game Development Project'), ('IOT', 'IoT / Embedded Project'), ('BLOCKCHAIN', 'Blockchain Project'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
