# Generated by Django 5.2.15 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0024_userproject_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question_generation_method',
            field=models.CharField(choices=[('RULE_BASED', 'Rule-Based Questions'), ('AI_POWERED', 'AI-Generated Questions')], default='RULE_BASED', max_length=20),
        ),
    ]
