# Generated by Django 5.2.15 on 2026-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0025_interviewsession_question_generation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinessassessment',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinessassessment',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
