# Generated by Django 5.2.15 on 2026-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0026_readinessassessment_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermatchresult',
            name='ai_roadmap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
