# Generated by Django 5.2.15 on 2026-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0027_careermatchresult_ai_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinessassessment',
            name='assessment_method',
            field=models.CharField(choices=[('RULE_BASED', 'Rule-Based Assessment'), ('AI_POWERED', 'AI-Powered Assessment')], default='RULE_BASED', max_length=20),
        ),
    ]
