# Generated by Django 5.2.15 on 2026-08-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0028_readinessassessment_assessment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employabilitybottleneck',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
