# Generated by Django 5.2.15 on 2026-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0029_employabilitybottleneck_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employabilitybottleneck',
            name='ai_action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employabilitybottleneck',
            name='ai_priority_gaps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employabilitybottleneck',
            name='ai_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
