# Generated by Django 5.2.15 on 2026-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0030_employabilitybottleneck_ai_action_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertransitionanalysis',
            name='ai_action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careertransitionanalysis',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careertransitionanalysis',
            name='ai_priority_gaps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careertransitionanalysis',
            name='ai_transferable_strengths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
